######################## default configuration ####################
baseURL = "http://example.org/"
languageCode = "en-us"
title = "Liva | Personal blog template"
theme = "liva-hugo"
summaryLength = "10"
pagination.pagerSize = 6
disqusShortname = ""
