######################## default configuration ####################
baseURL = "https://lovelyshark.net/"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "中国旅游指南"
theme = "liva-hugo"
summaryLength = 70
pagination.pagerSize = 6
disqusShortname = ""
