# --------------------------
# English language
# --------------------------
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2

# --------------------------
# Chinese language
# --------------------------
[zh-cn]
languageName = "中文"
languageCode = "zh-cn"
contentDir = "content/chinese"
weight = 1
